export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  LOAD_MORE_POPULAR_FAIL: 'LOAD_MORE_POPULAR_FAIL',
  LOAD_MORE_POPULAR_SUCCESS: 'LOAD_MORE_POPULAR_SUCCESS',
}